# Generated by Django 5.0 on 2023-12-22 20:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=2000)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('op1', models.CharField(max_length=500)),
                ('op2', models.CharField(max_length=500)),
                ('op3', models.CharField(max_length=500)),
                ('op4', models.CharField(max_length=500)),
                ('question_subject', models.CharField(max_length=10)),
                ('difficulty_level', models.IntegerField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=10)),
                ('test_descripition', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('class_group', models.IntegerField()),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_test.student')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_test.question')),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_test.readytest')),
            ],
        ),
        migrations.CreateModel(
            name='TestToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_test.student')),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_test.readytest')),
            ],
        ),
    ]
