# Generated by Django 5.0 on 2023-12-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtodo',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testtodo',
            name='was_done',
            field=models.BooleanField(default=False),
        ),
    ]
