# Generated by Django 5.0 on 2023-12-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_test', '0002_testtodo_grade_testtodo_was_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtodo',
            name='grade',
            field=models.FloatField(default=0),
        ),
    ]
