# Generated by Django 5.0 on 2024-01-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_test', '0003_alter_testtodo_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
